### ISSUE TITLE
Online-CMAQ Workflow failed with issue of importing f90nml on Hera

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [NOAA-EMC/AQM#46]
@chan-hoo 

I did download your latest online-cmaq workflow last night but failed with the following error message

Traceback (most recent call last):
  File "/scratch2/NCEPDEV/naqfc/Jianping.Huang/aqm.v7.0.20/ush/generate_FV3LAM_wflow.py", line 33, in <module>
    from set_FV3nml_sfc_climo_filenames import set_FV3nml_sfc_climo_filenames
  File "/scratch2/NCEPDEV/naqfc/Jianping.Huang/aqm.v7.0.20/ush/set_FV3nml_sfc_climo_filenames.py", line 28, in <module>
    from set_namelist import set_namelist
  File "/scratch2/NCEPDEV/naqfc/Jianping.Huang/aqm.v7.0.20/ush/set_namelist.py", line 74, in <module>
    import f90nml
ModuleNotFoundError: No module named 'f90nml'

Here is my work directory
/scratch2/NCEPDEV/naqfc/Jianping.Huang/aqm.v7.0.20/ush

module use ../modulefiles
 module load wflow_hera
conda activate regional_workflow
 python3 generate_FV3LAM_wflow.py

Is there anything that I am missing?

**Comment by chan-hoo** [comment]
@JianpingHuang-NOAA , please check your conda environment. This error means the conda environment 'regional_workflow' is not activated correctly.

**Comment by HaixiaLiu-NOAA** [comment]
@JianpingHuang-NOAA Has this been fixed? Can you close this issue? Thanks

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA says we can close this.
